// @generated by Cratis. Source: CratisAspire.SomeModule.SomeFeature.Listing.Listing, CratisAspire.SomeModule.SomeFeature.Listing.Listing. Time: 2026-09-06T08:30:09.3874220Z. Hash: FF9DCA3A43D56C77E9D588785CB18E24488546C6712E262E1110F040C6DC8DC4
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field, Guid } from '@cratis/fundamentals';

class AllListingsSortBy {

    constructor(readonly query: AllListings) {
    }

}

class AllListingsSortByWithoutQuery {

}


export class AllListings extends ObservableQueryFor<Listing[]> {
    readonly route: string = '/api/some-module/some-feature/listing/all-listings';
    readonly queryName: string = 'CratisAspire.SomeModule.SomeFeature.Listing.Listing.AllListings';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Listing[] = [];
    private readonly _sortBy: AllListingsSortBy;
    private static readonly _sortBy: AllListingsSortByWithoutQuery = new AllListingsSortByWithoutQuery();

    constructor() {
        super(Listing, true);
        this._sortBy = new AllListingsSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllListingsSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllListingsSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting] {
        return useObservableQuery<Listing[], AllListings>(AllListings, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Listing[], AllListings>(AllListings, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting] {
        return useSuspenseObservableQuery<Listing[], AllListings>(AllListings, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<Listing[], AllListings>(AllListings, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: Listing) => unknown, sorting?: Sorting): ChangeSet<Listing> {
        return useChangeStream<Listing, AllListings>(AllListings, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllListings, Listing[]> {
        return new ObservableQueryWhen<AllListings, Listing[]>(AllListings, condition);
    }
}

export class Listing {
    @field(Guid)
    id!: Guid;
    @field(String)
    name!: string;
    @field(String)
    eventSourceId!: string;
}
