<Project Sdk="Microsoft.NET.Sdk">
    <Sdk Name="Aspire.AppHost.Sdk" Version="13.5.3" />

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>TARGET_FRAMEWORK</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <AspireUseCliBundle>true</AspireUseCliBundle>
    </PropertyGroup>

    <PropertyGroup>
        <CratisDatabase>DATABASE</CratisDatabase>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="13.5.3" />
        <PackageReference Include="Cratis.Chronicle.Aspire" Version="*" />
    </ItemGroup>

    <ItemGroup Condition="'$(CratisDatabase)' == 'PostgreSQL'">
        <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
    </ItemGroup>

    <ItemGroup Condition="'$(CratisDatabase)' == 'MsSql'">
        <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.5.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CratisAspire\CratisAspire.csproj" />
    </ItemGroup>
</Project>
